sudo: false
notifications:
  email: false
language: ruby
rvm:
  - 2.3.3

script:
  - bundle exec rspec

gemfile:
  - Gemfile
  - Gemfile-rails-4.1.x
  - Gemfile-rails-4.2.x
  - Gemfile-rails-5.0.x
  - Gemfile-rails-5.1.x
